---
- hosts: all
  become: yes
  tasks:

    - name: Updating cache
      apt:
        update_cache: yes

    - name: Making Directory for image
      file:
        path: /home/valencia/destination
        state: directory
        mode: '0755'

    - name: Disable and stop Apache (Ubuntu)
      service:
        name: apache2
        state: stopped
        enabled: no
      when: ansible_distribution == 'Ubuntu'

    - name: Disable and stop Apache (CentOS)
      service:
        name: httpd
        state: stopped
        enabled: no
      when: ansible_distribution == 'CentOS'

    - name: Install Docker
      apt:
        name: docker.io
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: Copy Docker Image
      copy:
        src: /home/valencia/practice/practice.tar
        dest: /home/valencia/destination

    - name: Load Docker Image
      shell: docker load -i /home/valencia/destination/practice.tar


    - name: Run the Docker container
      command: docker run -d --name practice -p 80:80 practice
      args:
        creates: /var/run/docker.sock

    - name: Ensure container is running
      command: docker ps --filter "name=my-apache-server" --filter "status=running"
